// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"utf-8\"><link rel=\"icon\" href=\"/favicon.png\"><meta name=\"viewport\" content=\"width=device-width\"><title>AnyABI - The easiest way to fetch an ABI</title><meta name=\"twitter:title\" content=\"AnyABI - The easiest way to fetch an ABI\"><meta name=\"description\" content=\"Quickly grab the ABI for ANY EVM smart contract on ANY EVM chain.\"><meta name=\"twitter:description\" content=\"Quickly grab the ABI for ANY EVM smart contract on ANY EVM chain.\"><meta name=\"twitter:image\" content=\"https://anyabi.xyz/thumbnail.png\"><meta property=\"og:image\" content=\"https://anyabi.xyz/thumbnail.png\"><meta name=\"twitter:card\" content=\"summary_large_image\"><meta http-equiv=\"content-security-policy\" content=\"\"><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css\"></head><body><main class=\"container\"><h1><img src=\"/logo.png\" width=\"48\"> AnyABI</h1><article>The easiest way to fetch an ABI.</article><section><form role=\"search\"><fieldset role=\"group\"><select name=\"chain\"><option>Ethereum</option></select> <input name=\"address\" type=\"text\" placeholder=\"Address\"> <input type=\"submit\" value=\"Let&#39;s Go!\"></fieldset></form></section></main><!-- 100% privacy friendly analytics --><script async defer src=\"https://scripts.simpleanalyticscdn.com/latest.js\"></script><noscript><img src=\"https://queue.simpleanalyticscdn.com/noscript.gif\" alt=\"\" referrerpolicy=\"no-referrer-when-downgrade\"></noscript></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
