# https://taskfile.dev

version: '3'

vars:
  STATIC_DIR: 'static'

tasks:
  build:templ:
    cmds:
      - go run github.com/a-h/templ/cmd/templ@v0.3.819 generate -v

  build:
    cmds:
      - go build -o bin/anyabi .
    deps:
      - build:templ

  # The `live:` tasks below are used together for "dev" builds, and will hot-reload your entire project when there are code changes
  live:templ:
    cmds:
      - go run github.com/a-h/templ/cmd/templ@v0.3.819 generate --watch --proxy="http://localhost:8090" --open-browser=false -v

  live:server:
    cmds:
      - |
        go run github.com/air-verse/air@v1.52.3 \
        --build.cmd "go build -tags dev -o tmp/bin/main" \
        --build.bin "tmp/bin/main serve --dir ./pb_data" \
        --build.delay "20" \
        --build.exclude_dir "node_modules,data,public" \
        --build.include_ext "go" \
        --build.stop_on_error "false" \
        --misc.clean_on_exit true

  live:reload:
    cmds:
      - |
        go run github.com/air-verse/air@v1.52.3 \
        --build.cmd "go run github.com/a-h/templ/cmd/templ@v0.3.819 generate --notify-proxy" \
        --build.bin "true" \
        --build.delay "100" \
        --build.exclude_dir "" \
        --build.include_dir "$STATIC_DIR" \
        --build.include_ext "js,css"

  live:
    deps:
      - live:templ
      - live:reload
      - live:server

