# https://taskfile.dev

version: '3'

tasks:

  setup: 
    cmds:
      - go mod download
      - pnpm --prefix ui install

  backend_dev: air serve
  
  frontend_dev: pnpm --prefix ui dev

  frontend_build: pnpm --prefix ui build
  
  dev:
    deps: [backend_dev, frontend_dev]

  build:
    deps: [setup, frontend_build]
    cmds: 
      - go build -o bin/anyabi

  deploy: flyctl deploy
